pull_request_rules:
  - name: command dependabot to squash and merge
    conditions:
      - 'author=dependabot[bot]'
      - 'check-success~=Lint'
      - 'title~=bump [^\s]+ from ([\d]+)\..+ to \1\.'
      - 'base=dependabot'
    actions:
      review:
        type: APPROVE
      merge:
        method: squash