name: Lint, compile and test
on:
  push:
  pull_request:
    types: [opened, reopened]

jobs:
  ci:
    runs-on: ubuntu-latest
    name: Lint, compile and test
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Lint lockfile
        run: |
          npx lockfile-lint --type npm --path package-lock.json --validate-https --allowed-hosts npm

      - name: Install packages
        run: npm ci

      - name: Run lint
        run: npm run lint

      - name: Compile code
        run: npm run build

      - name: Run tests
        run: npm run test

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}